#!/bin/bash


usage()
{
	echo "Usage:"
	echo "   common-licenses -l"
	echo "        List all common licenses available"
	echo "   common-licenses -s <LICENSE_NAME>"
	echo "        Shows license content/text"
	echo "   common-licenses -p <LICENSE_NAME>"
	echo "        Prints license content/text"
	exit 1
}

MAGIC_PATH=/snap/common-licenses/current/usr/share/common-licenses

if [ "$1" ]; then
	while getopts 'lsp:' o;
	do
		case $o in
			l) ls $MAGIC_PATH
				;;
			s) licenses=($(ls $MAGIC_PATH))
		   	if [[ ${licenses[@]}  =~ $2 ]]
		   	then
				less "${MAGIC_PATH}/$2"
		   	else
				echo "Invalid license/passed value"
		   	fi
		   	;;
			p) licenses=($(ls $MAGIC_PATH))
		   	if [[ ${licenses[@]}  =~ $2 ]]
		   	then
				cat "${MAGIC_PATH}/$2"
		   	else
				echo "Invalid license/passed value"
		   	fi
		   	;;
			*)
				usage
				;;
			?)
				usage
				;;
		esac
	done
else
	usage
fi
