#!/bin/bash


usage()
{
	echo "Usage:"
	echo "   common-licenses -l"
	echo "        List all common licenses available"
	echo "   common-licenses -s <LICENSE_NAME>"
	echo "        Shows license content/text"
	echo "   common-licenses -p <LICENSE_NAME>"
	echo "        Prints license content/text"
	exit 1
}

if [ "$1" ]; then
	while getopts 'lsp:' o;
	do
		case $o in
			l) ls $SNAP/common-licenses/x1/current/usr/share/common-licenses/
				;;
			s) licenses=($(ls /usr/share/common-licenses/))
		   	if [[ ${licenses[@]}  =~ $2 ]]
		   	then
				less "/usr/share/common-licenses/$2"
		   	else
				echo "Invalid license/passed value"
		   	fi
		   	;;
			p) licenses=($(ls /usr/share/common-licenses/))
		   	if [[ ${licenses[@]}  =~ $2 ]]
		   	then
				cat "/usr/share/common-licenses/$2"
		   	else
				echo "Invalid license/passed value"
		   	fi
		   	;;
			*)
				usage
				;;
			?)
				usage
				;;
		esac
	done
else
	usage
fi
