name: common-licenses
base: core18
version: '0.1'
summary: A bash command that list and reads/print common licenses available
description: |
  A bash command that list and prints common licenses available in
  the system.

grade: stable
confinement: strict

parts:
  common-licenses:
    source: https://github.com/kirotawa/common-licenses.git
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp common-licenses $SNAPCRAFT_PART_INSTALL/bin
    stage-packages:
      - base-files
apps:
  common-licenses:
    command: common-licenses
